version: '3'
services:
  jekyll-serve:
    image: jekyll/jekyll:4.0
    user: root
    volumes:
      - ".:/srv/jekyll"
    ports:
      - 4000:4000
    command: 'jekyll serve'
    environment:
          JEKYLL_UID: 1001
          JEKYLL_GID: 1001

